name: Dialed-In-Backend-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.4

    - name: Setup .env file
      run: |
        echo DATABASE_HOST=${{ vars.DATABASE_HOST }} >> .env
        echo DATABASE_DRIVER=${{ vars.DATABASE_DRIVER }} >> .env
        echo POSTGRES_USER=${{ vars.POSTGRES_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_DB=${{ vars.POSTGRES_DB }} >> .env
        echo POSTGRES_PORT=${{ vars.POSTGRES_PORT }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }} >> .env

    - name: Build Docker image
      run: docker compose build

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Run Tests
      run: make test-all

    - name: Health Check Server
      run: curl -X GET http://localhost:3000/v1/healthcheck | grep "available" 
